package com.facebook;


public enum LoggingBehavior {

   // $FF: synthetic field
   private static final LoggingBehavior[] $VALUES = new LoggingBehavior[]{REQUESTS, INCLUDE_ACCESS_TOKENS, INCLUDE_RAW_RESPONSES, CACHE, APP_EVENTS, DEVELOPER_ERRORS, GRAPH_API_DEBUG_WARNING, GRAPH_API_DEBUG_INFO};
   APP_EVENTS("APP_EVENTS", 4),
   CACHE("CACHE", 3),
   DEVELOPER_ERRORS("DEVELOPER_ERRORS", 5),
   GRAPH_API_DEBUG_INFO("GRAPH_API_DEBUG_INFO", 7),
   GRAPH_API_DEBUG_WARNING("GRAPH_API_DEBUG_WARNING", 6),
   INCLUDE_ACCESS_TOKENS("INCLUDE_ACCESS_TOKENS", 1),
   INCLUDE_RAW_RESPONSES("INCLUDE_RAW_RESPONSES", 2),
   REQUESTS("REQUESTS", 0);


   private LoggingBehavior(String var1, int var2) {}
}
